# Generated by Django 3.0.5 on 2020-05-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_disease_drug_ussdquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
